pipelines:
  default:
    - step:
        name: Build
        image: node:8
        caches:
          - node
        script:
          - npm install
          - npm run build
        artifacts:
          - build/**
    - step:
        name: Package
        image: gliderlabs/alpine:3.4
        script:
          - apk add --no-cache zip
          - zip -r quickpick.zip build
        artifacts:
          - quickpick.zip
    - step:
        name: Deploy
        deployment: production
        image: atlassian/default-image:2
        script:
          - curl -X POST --user "${BB_AUTH_STRING}" "https://api.bitbucket.org/2.0/repositories/${BITBUCKET_REPO_OWNER}/${BITBUCKET_REPO_SLUG}/downloads" --form files=@"quickpick.zip"